"""Added action table

Revision ID: 3e5951a401e3
Revises: b22b9a54f275
Create Date: 2022-12-18 16:47:25.084406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5951a401e3'
down_revision = 'b22b9a54f275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('enemies', 'damage',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('enemies', 'damage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('action')
    # ### end Alembic commands ###
