missed_data = 'Not all data was given'
unexpected_duplicate_error = 'Unexpected error with duplicate key'
wrong_credentials = 'Wrong username or password'
expired_token = 'Token has expired'
wrong_token = 'Wrong token'
not_found = 'Not found'
wrong_index = 'Wrong index of array'
